version: "2"
services:
  rest-api:
    build: .
    ports:
      - "5005:5005"
    # environment:
    #   - 

    links:
      - mongodb
  mongodb:
    image: mongo
    volumes:
      - /data/mongodb/db:/data/db
    ports:
      - "27017:27017"